### ISSUE TITLE
Error when Publishing

### ISSUE THREAD

**Issue by Torbikini** [Earu/GSW-action#1]
Hello! I just discovered this and would love to make use of it, but I'm having some issues getting it to work. The error I'm having is:
```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 399999996. Received 400000001
    at boundsError (internal/buffer.js:72:9)
    at checkBounds (internal/buffer.js:41:5)
Error: The value of "offset" is out of range. It must be >= 0 and <= 399999996. Received 400000001
    at checkInt (internal/buffer.js:60:3)
    at writeU_Int32LE (internal/buffer.js:678:3)
    at Buffer.writeUInt32LE (internal/buffer.js:691:10)
    at createGMA (/home/runner/work/_actions/Earu/GSW-action/V2.1/index.js:206:18)
    at run (/home/runner/work/_actions/Earu/GSW-action/V2.1/index.js:306:3)
    at Object.<anonymous> (/home/runner/work/_actions/Earu/GSW-action/V2.1/index.js:321:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10) {
  code: 'ERR_OUT_OF_RANGE'
```

Would you happen to know what I'm doing wrong? I was able to upload the content pack normally via gmpublisher but, this is going to make working in a team a lot easier.

**Comment by Earu** [comment]
Hey there thank you for the report. Just looking at the stacktrace like that, won't help much. Do you have something I can use to reproduce this behavior?

**Comment by Torbikini** [comment]
Yeah, totally - what would you need from me? I could send you a link with the files or invite you to the repo. Not sure what you would need in order to debug this.

**Comment by Earu** [comment]
You could either make your repo public or provide the files. Whichever you prefer. Or you can also keep it all private, I respect that.

**Comment by Torbikini** [comment]
I sent you an invite to the repo if that's alright with you. It's mainly private just because there's no point in it being public in my opinion. The link to the repo is [here](https://github.com/Simple-Craft/TTT-Content-Packs/invitations).

**Comment by Earu** [comment]
Alright, thanks. I think I found the issue. By default the path for building the .gma is the root of the repository, but in your case the root of your addon would be in ` sttt_content_2_playermodels`. You should specify the ` addon-path`  argument, for example: https://github.com/Earu/EasyChat/blob/master/.github/workflows/workshop.yml#L41

**Comment by Torbikini** [comment]
Thank you for the response. I had it set to `addon-path: "sttt_content_2_playermodels"` would that not be correct syntax?

**Comment by Earu** [comment]
I'm not sure in theory its correct but GitHub actions are a bit special. If you're using the Checkout action for getting the repo, you can use the env.GITHUB_WORKSPACE to get the path to your repo on the machine. So you could append "/sttt_content_2_playermodels" and then it might work. I suspect it's a path problem.

**Comment by Torbikini** [comment]
I was able to get the path issue fixed, but I'm still having the issue: 
![image](https://user-images.githubusercontent.com/841055/132971709-9bc1691c-3064-43e4-b3d9-fbd20413ae23.png)

Not sure if there's a way to get you additional logs, but I have no idea.

**Comment by Earu** [comment]
Alright so what you can do now is test it with a repo with less things in it. My guess is that there might be too many large files in your repo.

**Comment by Torbikini** [comment]
Gotcha, if I had to guess it's probably a limitation of the library that you're using. I was able to publish it via a tool locally so I have no idea. Thank you for looking into it though, I'm probably just going to have to stick with manually uploading to the workshop, unfortunately. Feel free to close this if you want this might require a decent amount of investigating.
